all: pc-mutex-cv.out pc-semaphore.out

pc-mutex-cv.out: pc-mutex-cv.c
	gcc pc-mutex-cv.c pc-mutex-cv.h -o pc-mutex-cv.out -lpthread

pc-semaphore.out: pc-semaphore.c
	gcc pc-semaphore.c pc-semaphore.h -o pc-semaphore.out -lpthread