all: pc-mutex-cv.out pc-semaphore.out

pc-mutex-cv.out: pc-mutex-cv.c
	gcc pc-mutex-cv.c -o pc-mutex-cv.out -lpthread

pc-semaphore.out: pc-semaphore.c
	gcc pc-semaphore.c -o pc-semaphore.out -lpthread